let startCalc = document.getElementById('start'),
    blocks = document.querySelectorAll("div.result-table > [class*='value']"),
    inputField = document.getElementsByClassName("expenses-item"),
    btn1 = document.getElementsByTagName('button')[0],
    btn2 = document.getElementsByTagName('button')[1],
    btn3 = document.getElementsByTagName('button')[2],
    btn4 = document.getElementsByTagName('button')[3],
    optionalExp = document.querySelectorAll("[class='optionalexpenses-item']"),
    chooseIncome = document.querySelector('.choose-income'),
    checkSavings = document.querySelector('.checksavings'),
    sumChoose = document.querySelector('.choose-sum'),
    percent = document.querySelector('.choose-percent'),
    year = document.querySelector('.year-value'),
    month = document.querySelector('.month-value'),
    day = document.querySelector('.day-value');